export const SinglePropertyReviewStyles = {
  mainContainerBox: { px: { md: 1, xs: 1 }, mt: { md: 0, xs: 4 } },
  reviewTitle: { mb: 3, display: 'flex', alignItems: 'center', ml: { md: 0, xs: 2 } },
  reviewTitleIcon: { fontSize: '30px', mr: 1 },
  reviewContainerBox: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 2,
    justifyContent: 'space-between',
    '& > *': {
      flex: { xs: '1 1 100%', md: '1 1 calc(50% - 16px)' },
      minWidth: { xs: '100%', md: 'calc(50% - 16px)' },
      maxWidth: { xs: '100%', md: 'calc(50% - 16px)' },
    },
  },
  reviewBox: {
    p: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
    maxWidth: '300px',
  },
  reviewDetailsBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
  },
  reviewNameBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
  },
  reviewAvatarBox: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    backgroundColor: '#007BFF',
    color: '#fff',
    fontWeight: 'bold',
  },
  reviewName: { fontWeight: 'bold' },
  reviewRatingIcons: {
    '& svg': { fontSize: '16px' },
  },
  showMoreButton: { textAlign: 'center', mt: 2 },
} as const;
