export const PropertyAmenityStyles = {
  mainContainerBox: {
    display: 'flex',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    alignItems: { xs: 'center', md: 'flex-start' },
    mt: 6,
    flexDirection: { xs: 'column', md: 'row' },
  },
  leftContainerBox: { maxWidth: 800, p: 2, pl: { md: 0, xs: 2 }, flex: '1 1 60%' },
  divider: { mt: 3, mb: 3 },
  avatarBox: { display: 'flex', alignItems: 'center', mb: 3 },
  avatar: {
    width: 56,
    height: 56,
    background: 'rgb(219,10,98)',
    color: 'white',
    mr: 2,
    fontSize: 24,
  },
  showMoreButton: { my: 3 },
  unshownAmenitiesBox: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 2,
    justifyContent: 'space-between',
  },
  unshownAmenitiesCard: {
    flex: { xs: '1 1 100%', md: '1 1 calc(50% - 16px)' },
    minWidth: { xs: '100%', md: 'calc(50% - 16px)' },
    maxWidth: { xs: '100%', md: 'calc(50% - 16px)' },
  },
  customDivider: { my: 3, display: { md: 'none', xs: 'block' } },
  rightContainerBox: {
    p: 2,
    maxWidth: 400,
    flex: '1 1 35%',
    border: '1px solid rgba(0, 0, 0, 0.1)',
    mt: { xs: 0, md: 2 },
    borderRadius: '15px',
    boxShadow: '0px 4px 10px rgba(0, 0, 0, 0.1), 0px 2px 5px rgba(0, 0, 0, 0.06)',
    mx: { xs: 2, md: 0 },
  },
  datePickBox: { display: 'flex', flexDirection: 'row', gap: 2, mt: 2 },
  datePick: { flex: '1' },
  reserveButton: { mt: 2, width: '100%', background: 'rgb(219,10,98)', py: 1 },
  priceBox: { mt: 2 },
  priceBoxTypography1: { display: 'flex', justifyContent: 'space-between' },
  priceBoxTypography2: { display: 'flex', justifyContent: 'space-between', mt: 1 },
  priceBoxDivider: { my: 2 },
  priceBoxTypography3: { display: 'flex', justifyContent: 'space-between', mt: 2 },
  priceBoxBoldTypography: { fontWeight: 'bold' },
};
